Traducción al español de es/book/README.md (Falta cambiar nombre de links)
RustLangES/nushell.github.io pull request #6
Opened 2024-11-22 22:13 UTC by CosmoCarpincho

2024-11-22 22:18 UTC, stifskere commented on es/book/README.md
> +## Contribuir
contribuyendo

2024-11-22 22:20 UTC, stifskere requested changes
Deje el comentario ahi

2024-11-22 22:44 UTC, CosmoCarpincho commented on es/book/README.md
> +## Contribuir
Listo.

Contribuir -> Contribuyendo

2024-12-29 03:04 UTC, jd-apprentice approved these changes
LGTM!

2024-12-29 03:05 UTC, stifskere commented
No que estaba cerrada esta?

2024-12-29 03:06 UTC, jd-apprentice commented
> No que estaba cerrada esta?

Viendo la fecha, parece ser que quedo olvidada/desactualizada

2024-12-29 03:06 UTC, merged

2024-12-29 03:07 UTC, stifskere commented
toma merge, que sea lo que dios quiera